version: "3"
services:
  database:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  back:
    build: ./back
    ports:
      - "4000:4000"
    volumes:
      - ./back:/home/app
      #- /home/app/node_modules
    environment:
      DATABASE_URL: postgres://postgres:postgres@database:5432/postgres
      JWT_KEY: ChangeMeImCritical
    depends_on:
      - database

  front:
    build: ./front
    ports:
      - "3000:3000"
    volumes:
      - ./front:/home/app
      #- /home/app/node_modules
      - /home/app/.next

volumes:
  db:
    driver: local
