version: '3'
services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data

  front: 
    image: ./front
    ports: 
      - '3000:3000'
    volumes:
      - ./front:/home/app
      - /home/app/node_modules

  back:
    build: ./back
    ports:
      - '4000:4000'
    volumes:
      - ./back:/home/app
      - /home/app/node_modules
    depends_on:
      - database  

volumes:
  database: