import React from "react";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { LayoutAdmin } from "@/components/LayoutAdmin";

type Props = {};

const inter = Inter({ subsets: ["latin"] });

const AdminPage = (props: Props) => {
  return (
    <LayoutAdmin>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="text-3xl font-bold font-prompt text-neutral-500">
        Pannel Administrateur
      </main>
    </LayoutAdmin>
  );
};

export default AdminPage;
